name: event output
on:
  workflow_dispatch:
    inputs:
      ipwhite:
        description: 'add white ip'     
        required: false
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: shell event result
        run: |
         cat ${{ github.event_path }}
